service: pya-website-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    SMTP_HOST: ${env:SMTP_HOST}
    SMTP_PORT: ${env:SMTP_PORT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    SMTP_TO: ${env:SMTP_TO}
    SMTP_FROM: ${env:SMTP_FROM}
  deploymentBucket:
    name: serverless-kerbrum-deployments
    serverSideEncryption: AES256

package:
  individually: true
  exclude:
    - .git/**
    - .vscode/**
    - img/**
    - pages/**
    - css/**
    - node_modules/aws-sdk/** 
  include:
    - img/header/LOGOO.png

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
